# Generated by Django 5.0.2 on 2024-03-07 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_name'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='blacklisted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted', to='participant.participant'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='participant.participant'),
        ),
    ]
